# Generated by Django 2.1.1 on 2018-10-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('age', models.IntegerField(max_length=3)),
                ('mobile_number', models.IntegerField(max_length=11)),
            ],
        ),
    ]
