# Generated by Django 2.1.1 on 2018-10-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_user_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_list',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
