# Generated by Django 2.1.1 on 2018-10-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20181002_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_list',
        ),
    ]
